SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `books` (
  `id` int(11) NOT NULL,
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_slovenian_ci NOT NULL,
  `author` varchar(255) CHARACTER SET utf8 COLLATE utf8_slovenian_ci NOT NULL,
  `description` text CHARACTER SET utf8 COLLATE utf8_slovenian_ci NOT NULL,
  `content` text CHARACTER SET utf8 COLLATE utf8_slovenian_ci NOT NULL,
  `cover` varchar(255) CHARACTER SET utf8 COLLATE utf8_slovenian_ci NOT NULL,
  `price` int(11) NOT NULL,
  `category_id` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `books` (`id`, `name`, `author`, `description`, `content`, `cover`, `price`, `category_id`) VALUES
(1, 'Harry Potter - Jetnik iz Azkabana', 'J.K.Rowling', 'Harry Potter - Jetnik iz Azkabana (Žepnica).', 'Trinajstletni Harry Potter ima med počitnicami same težave… Mladi vajenec čarovništva po nesreči povzroči, da se zlobna (bunkeljska) gostja družine napihne kakor orjaški balon in odleti pod strop. A čaranje med počitnicami je strogo prepovedano…\r\n\r\nTako se Harry s svojim težkim zabojem in sovo Hedwig poda v temne londonske ulice. Ko se končno prične pouk v tretjem letniku Bradavičarke, akademije za čarovnike in čarovnice, pa Harry in prijatelji izvedo, da je na begu Sirius Black, jetnik iz Azkabanske ječe in Mrlakensteinov zvesti podanik. Jetnik iz Azkabana je tretji del iz serije knjig o Harryju Potterju, mladem čarovniku, ki bije bitko z najtemnejšim čarovnikom vseh časov - Mrlakensteinom.', 'https://www.emka.si/wcsstore/MKCAS/img/catalog/9789610106104/646x1000/9789610106104.jpeg', 15, 1),
(2, 'Harry Potter - Dvorana Skrivnosti', 'J.K.Rowling', 'Harry Potter - Dvorana Skrivnosti (Žepnica).', 'Harry Potter čaka, da minejo mukotrpne počitnice pri stricu in teti, ko ga preseneti drobni hišni vilinec. Ta Harryja posvari, naj ne hodi na Bradavičarko, saj ga tam čaka smrtna nevarnost. A deček ga ne posluša. Veselje ob ponovnem snidenju s prijatelji žal ne traja dolgo. Kaj se dogaja?\r\n\r\nNa čarovniški akademiji nekdo študente z uroki spreminja v kamnite kipe. Harry je vedno ob nepravem času na nepravem mestu in po šoli se začnejo širiti govorice, da za napadi stoji on.\r\n\r\nJ. K. Rowling (1965) je uspešna in vplivna britanska pisateljica. Serijo knjig o mladem čarovniku je bolj za svojo dušo kot z željo po uspehu začela pisati kot brezposelna mati samohranilka v Edinburgu na Škotskem in obogatela. Po sedmih romanih iz serije o Harryju Potterju je posnetih osem filmov.', 'https://www.emka.si/wcsstore/MKCAS/img/catalog/9789610106036/646x1000/9789610106036.jpeg', 14, 1),
(3, 'Harry Potter - Kamen Modrosti ', 'J.K.Rowling', 'Harry Potter - Kamen Modrosti (Žepnica).', '1. knjiga kronike dogodivščin mladega čarovnika Harryja Potterja. Harry je sin slavnih staršev. Šele na svoj 11. rojstni dan izve, kdo pravzaprav je, saj sta mu teta in stric, bunkeljna, pri katerih živi, zamolčala njegovo mogočno preteklost. Harry je sprejet na Bradavičarko, šolo za čarovništvo, in skupaj s prijateljema se upre mračnim silam, ki so mu umorile starše. ​Harry Potter je enajstletni fantič, ki živi pri stricu in teti. Spati mora v shrambi pod stopnicami, debeli in zlobni bratranec Dudley pa ga ima za živo igračo. Ko nekega dne Harry prejme skrivnostno pismo, mu v sivino vsakdanjika posije svetla luč, saj izve, da je čarovnik. Znajde se na Bradavičarki, akademiji za čarovnike, kjer spozna nove prijatelje. Toda za debelimi zidovi starodavne šole prežijo nanj tudi nevarnosti.\r\n\r\nKamen modrosti je prva knjiga v zbirki o mladem čarovniku, ki je obnorela mlade in stare ljubitelje književnosti širom sveta.\r\n\r\n​Roman je bil večkrat nagrajen (nagrada Nestlé Smarties, britanska otroška knjiga leta), zato ni čudno, da bralca kar posrka v svet čarovnikov, zmajev in pošasti.', 'https://www.emka.si/wcsstore/MKCAS/img/catalog/9789610105435/646x1000/9789610105435.jpeg', 13, 1),
(4, 'Bread street kitchen - Gordon Ramsay: Recepti za slastne zajtrke, kosila in večerje, ki jih lahko pripravite doma ', 'Gordon Ramsay', 'Zajtrk, večerja in vse vmes – v tej knjigi boste našli 100 čudovitih novih receptov priznanega chefa Gordona Ramsayja in njegove nagrajene ekipe iz restavracije Bread Street Kitchen. Pod recepti v tej knjigi je podpisan svetovno znani chef Gordon Ramsay. Odlikuje jih uporaba svežih sestavin in preprostih tehnik priprave hrane. Zato je prav vsak recept primeren za pripravo doma in je lahko navdih za odličen obrok ne glede na del dneva. Začnite torej dan z dišečo ovseno kašo s kompotom iz jabolk in cimeta ali s krepko omleto z divjimi gobami in grojerjem ter zdravim zelenim sokom; za brunch postrezite pregrešno dobre palačinke iz rikote z banano in ingverjevim maslom; kruhke s karamelizirano čebulo, pestom in sirom taleggio ter piščančje perutničke s tamarindo delite s prijatelji; preprosta recepta za piščančjo solato beng beng in govejo tagliato bosta popestrila običajni večerni obrok. In zakaj ne bi med druženjem konec tedna začeli z neverjetno osvežilno pijačo iz vodke, limete in be ...', 'Zajtrk, večerja in vse vmes – v tej knjigi boste našli 100 čudovitih novih receptov priznanega chefa Gordona Ramsayja in njegove nagrajene ekipe iz restavracije Bread Street Kitchen.\r\n\r\nPod recepti v tej knjigi je podpisan svetovno znani chef Gordon Ramsay. Odlikuje jih uporaba svežih sestavin in preprostih tehnik priprave hrane. Zato je prav vsak recept primeren za pripravo doma in je lahko navdih za odličen obrok ne glede na del dneva.\r\n\r\nZačnite torej dan z dišečo ovseno kašo s kompotom iz jabolk in cimeta ali s krepko omleto z divjimi gobami in grojerjem ter zdravim zelenim sokom; za brunch postrezite pregrešno dobre palačinke iz rikote z banano in ingverjevim maslom; kruhke s karamelizirano čebulo, pestom in sirom taleggio ter piščančje perutničke s tamarindo delite s prijatelji; preprosta recepta za piščančjo solato beng beng in govejo tagliato bosta popestrila običajni večerni obrok. In zakaj ne bi med druženjem konec tedna začeli z neverjetno osvežilno pijačo iz vodke, limete in bezga, za glavno jed pripravili pečene račje prsi z dušenim ješprenjem in omako iz robidnic, za piko na i pa poskrbeli z ananasovim karpačem s kokosovim sorbetom?\r\n\r\nDoma pripravljena hrana še nikoli ni bila tako okusna!', 'https://www.emka.si/wcsstore/MKCAS/img/product/48t_2017/gordon-ramsay-maketa_500.jpg', 33, 4),
(6, 'Jakec in breskev velikanka ', 'Roald Dahl', 'Jakec Henrik Konjar je sirota in živi z zlobnima tetama Cvek in Cmok. Zanju gara kot črna živina. Nekega dne pa sreča starčka v zeleni obleki, ki mu podari majhne krokodilje jezike s posebno magično močjo.\r\nPo nesreči se Jakcu razsujejo po tleh in v bližini stare breskve poniknejo v tla. Naslednjega dne je tam ogromna breskev velikanka; v njej prebivajo nenavadna bitja in Jakec se z njimi odpravi na razburljivo avanturo ...\r\n\r\nKnjigo krasijo ilustracije Quentina Blakea, Milan Dekleva pa je opravil izjemno prevajalsko delo in mladinsko klasiko znova približal bralcem.', 'Jakec Henrik Konjar je sirota in živi z zlobnima tetama Cvek in Cmok. Zanju gara kot črna živina. Nekega dne pa sreča starčka v zeleni obleki, ki mu podari majhne krokodilje jezike s posebno magično močjo.\r\nPo nesreči se Jakcu razsujejo po tleh in v bližini stare breskve poniknejo v tla. Naslednjega dne je tam ogromna breskev velikanka; v njej prebivajo nenavadna bitja in Jakec se z njimi odpravi na razburljivo avanturo ...\r\n\r\nKnjigo krasijo ilustracije Quentina Blakea, Milan Dekleva pa je opravil izjemno prevajalsko delo in mladinsko klasiko znova približal bralcem.', 'https://www.emka.si/wcsstore/MKCAS/img/product/36t_2016/9789610110439_500.jpg', 12, 2),
(7, 'Čarli in tovarna čokolade ', 'Roald Dahl', 'Ponatis. Poleg nepozabne Matilde je Čarli najbolj uspešen knjižni lik legendarnega angleškega pisatelja Roalda Dahla. Čarli nima bogatih staršev, toplega doma in nobene igrače. Ima pa veliko srečo!   Z najdenim kovancem si je kupil čokolado, v kateri je bila vstopnica v skrivnostno tovarno čokolade. Tam ga poleg čokoladne reke, vročega sladoleda, karamelnega rudnika, mavričnih solzic in televizične čokolade čaka še eno, čisto neverjetno presenečenje. Roald Dahl je bil vohun, odličen pilot bojnega letala, zgodovinar, ki se je spoznal na čokolado, in izumitelj medicinskih pripomočkov. Je tudi avtor knjig Čarli in tovarna čokolade, Matilda, VDV in mnogih drugih izvrstnih zgodb. Ostaja najboljši otroški pisatelj na svetu. ...', 'Poleg nepozabne Matilde je Čarli najbolj uspešen knjižni lik legendarnega angleškega pisatelja Roalda Dahla.\r\n\r\nČarli nima bogatih staršev, toplega doma in nobene igrače. Ima pa veliko srečo!\r\n \r\nZ najdenim kovancem si je kupil čokolado, v kateri je bila vstopnica v skrivnostno tovarno čokolade. Tam ga poleg čokoladne reke, vročega sladoleda, karamelnega rudnika, mavričnih solzic in televizične čokolade čaka še eno, čisto neverjetno presenečenje.\r\n\r\nRoald Dahl je bil vohun, odličen pilot bojnega letala, zgodovinar, ki se je spoznal na čokolado, in izumitelj medicinskih pripomočkov. Je tudi avtor knjig Čarli in tovarna čokolade, Matilda, VDV in mnogih drugih izvrstnih zgodb. Ostaja najboljši otroški pisatelj na svetu.', 'https://www.emka.si/wcsstore/MKCAS/img/product/27t_2016/9788611176550-zep_500.jpg', 13, 2),
(8, 'Gromska strela!', 'Arto Paasilinna', 'Finski narod ima še vedno svoje napake. Vsesplošno grešnost, pohlepnost in najrazličnejše oblike hudobije. So pa Finci vseeno edini narod, ki ne premore niti enega norca. ', 'Na kriznem sestanku finskih bogov se izriše jasen sklep – ljudje vanje ne verjamejo več. Vrhovni bog Gromovnik zato na Zemljo pošlje svojega sina, da bi finski narod spreobrnil k pravi veri. Hitro se izkaže, da bo imelo božanstvo polne roke dela – v deželi vladata apatija in pomanjkanje vsakršnih vrednot. A Gromovnikov sin ima skrivno orožje, s katerim zna spraviti k pameti tudi najbolj nejeverne Tomaže, sekira pa mu zares pade v med, ko nazadnje odkrije številne hvaležne ovčice v finskih umobolnicah … Roman Gromska strela!, ki je v finščini izšel leta 1984, prinaša avtorjevo priljubljeno kombinacijo čudaških likov in družbene parodije.', 'https://www.dobreknjige.si/Images/Img_00076491_big.gif', 13, 5),
(9, 'Božanska komedija. Pekel - Vice - Raj', 'Dante Alighieri', 'Spomenik klasične književnosti v prevodu dr. Andreja Capudra, z reprodukcijami grafik Gustava Doréja.', 'Spomenik klasične književnosti v prevodu dr. Andreja Capudra, z reprodukcijami grafik Gustava Doréja.\r\n\r\nDante nas v svoji umetniško nedosežni Comedii ne popelje le skozi tri možne posmrtne svetove, kot se nam razodevajo v krščanskem izročilu, ampak se v njej sprehodi po vrhovih tedanje znanosti, umetnosti in politike, predvsem pa nam v verzih razkriva človeka – od brezen njegove grešnosti do višav njegove krepostnosti. Eno največjih mojstrovin svetovne literature v prepesnitvi Andreja Capudra, ki je zanjo prejel Sovretovo nagrado, dodatno bogatijo Doréjeve ilustracije.\r\n\r\nLahko bi rekli, da je Dantejeva Božanska komedija do danes nepresežena pesniška umetnina, čeprav je nastala na prehodu davnega 13. v 14. stoletje. Seveda pa ni le umetnina brez primere, ki v treh knjig (Pekel, Vice, Raj) in skupaj 100 spevih nudi bralcu na tisoče verzov, ampak tudi večna odslikava človeškega življenja, ki je razprto »med pekel in nebo«, kot bi rekel naš Prešeren. Delo so presajali v slovenščino številni ugledni literati, malokdo od njih pa je znal Dantejeve verze tako dobro preliti v našo materinščino, kot je to uspelo Andreju Capudru. Naša izdaja Božanske komedije je obogatena z reprodukcijami grafik Gustava Doréja.', 'https://www.emka.si/wcsstore/MKCAS/img/product/leposlovje/159785/9789612185824_500.jpg', 120, 5),
(10, 'Anina kuhinja po navdihu', 'Ana Žontar Kristanc', 'Knjiga Anina kuhinja po navdihu vsebuje več kot 100 preizkušenih in poslikanih receptov, ki me zadnja leta najbolj navdušujejo.', 'Knjiga Anina kuhinja po navdihu vsebuje več kot 100 preizkušenih in poslikanih receptov, ki me zadnja leta najbolj navdušujejo. V knjigi boste tako našli mnogo zanimivih in uporabnih receptov, kot je pripravljena pica v ponvi, pa čokoladni kolač iz ajdove kaše in japonske nekaj centimetrov debele puhaste palačinke, domača azijska sladko-kisla omaka in še mnogo več.', 'https://www.emka.si/wcsstore/MKCAS/img/product/48t_2018/9789619398357_500.jpg', 22, 4),
(11, 'Romeo in Julija', 'William Shakespeare', 'Zbirka slovenskih in svetovnih leposlovnih del je prilagojena zlasti srednješolskemu izboru domačega in maturitetnega branja ter aktivnemu literarnemu pouku. Teksti so strokovno predstavljeni s spremnimi besedili, ki vključujejo: literarnozgodovinsko predstavitev avtorja, njegovega časa in dela, poglobljeno analizo in interpretacijo literarnih prvin zunanje in notranje zgradbe, jezika in sloga, izbor mnenj o delu, vprašanja, naloge in teme.', 'Zbirka slovenskih in svetovnih leposlovnih del je prilagojena zlasti srednješolskemu izboru domačega in maturitetnega branja ter aktivnemu literarnemu pouku. Teksti so strokovno predstavljeni s spremnimi besedili, ki vključujejo: literarnozgodovinsko predstavitev avtorja, njegovega časa in dela, poglobljeno analizo in interpretacijo literarnih prvin zunanje in notranje zgradbe, jezika in sloga, izbor mnenj o delu, vprašanja, naloge in teme.', 'https://www.emka.si/wcsstore/MKCAS/img/catalog/9788634124682/646x1000/9788634124682.jpeg', 17, 3),
(12, 'Mulčki: 6 minutne zgodbe', 'Charles Schultz', 'Kdo je Snoopyjev najboljši prijatelj? Bo Charlieju Brownu končno uspelo brcniti žogo? Se bo Linus sploh kdaj znebil svoje odejice ali bo odrasel z njo? Odprite to zakladnico šestih najboljših zgodb o Mulčkih in ugotovite! Odlične petminutne zgodbe za lahko noč in za vse oboževalce Mulčkov!', 'Kdo je Snoopyjev najboljši prijatelj? Bo Charlieju Brownu končno uspelo brcniti žogo? Se bo Linus sploh kdaj znebil svoje odejice ali bo odrasel z njo? Odprite to zakladnico šestih najboljših zgodb o Mulčkih in ugotovite! Odlične petminutne zgodbe za lahko noč in za vse oboževalce Mulčk', 'https://www.emka.si/wcsstore/MKCAS/img/catalog/9789616145411/646x1000/9789616145411.jpeg', 18, 2),
(13, 'Gordon Ramsay Ultimate Fit Food: Mouth-watering recipes to fuel you for life', 'Gordon Ramsay', 'The definitive cookbook for eating well to achieve optimum health and fitness, by one of the world\'s finest chefs and fitness fanatic, Gordon Ramsay.', 'The definitive cookbook for eating well to achieve optimum health and fitness, by one of the world\'s finest chefs and fitness fanatic, Gordon Ramsay.', 'https://www.emka.si/wcsstore/MKCAS/img/product/1/97814736/9781473652279.jpg', 39, 4),
(14, 'Babica vas pozdravlja in se opravičuje', 'Fredrik Backman', 'Babica vsako noč Elso odpelje v Miamas. Tam so Elso povišali v vitezinjo. Tam sme jahati na oblakastih živalih in ima svoj meč, in odkar hodi tja, je nikoli več ni strah spati same. Kajti v Miamasu nihče ne reče, da dekleta ne smejo vstopiti v viteški red; tam gore segajo do neba, taborni ognji nikoli ne ugasnejo in nobena pametnjakovička ti ne poskuša raztrgati šala z emblemom Gryfondoma.\r\n\r\nBabica tudi pravi, da v Miamasu nihče ne zapira vrat, kadar gre na stranišče', 'Elsa je skoraj osem let stara deklica. Za svoja leta je zelo zrela, kar pa je, kot pravijo odrasli, samo drug izraz za "strašansko težavna za svoja leta". Skupaj s pisano druščino sosedov živi v skupnosti najemniških stanovanj. Z babico, svojo superjunakinjo, se skupaj podajata v pravljično deželo Miamas. Kljub svoji modrosti in branju veliko kakovostne literature (Harryja Potterja in stripov o Supermanu ter Možeh X) pa po babičini smrti Elsa ugotovi, da še marsičesa ne ve. Babica jo namreč pred smrtjo pošlje na lov na zaklad, ki deklico skozi spoznavanje življenjskih zgodb sosedov, mame in babice vodi po poti odraščanja. In do ugotovitve, da najboljše pravljice niso nikoli popolnoma resnične in nikoli popolnoma izmišljene. Topel in z obilico humorja napisan roman avtorja Moža z imenom Ove nam prepričljivo prikaže svet, kot ga vidi sedemletna deklica, ki si okolico, ljudi in dogodke osmišlja s pomočjo babičinega pravljičnega sveta.', 'https://www.dobreknjige.si/Images/Img_00027651_big.gif', 17, 5),
(15, 'Ta veseli dan ali Matiček se ženi', 'Anton Tomaž Linhart', 'Zbirka slovenskih in svetovnih leposlovnih del je prilagojena zlasti srednješolskemu izboru domačega in maturitetnega branja ter aktivnemu literarnemu pouku. Teksti so strokovno predstavljeni s spremnimi besedili, ki vključujejo: literarnozgodovinsko predstavitev avtorja, njegovega časa in dela, poglobljeno analizo in interpretacijo literarnih prvin zunanje in notranje zgradbe, jezika in sloga, izbor mnenj o delu, vprašanja, naloge in teme.', 'Zbirka slovenskih in svetovnih leposlovnih del je prilagojena zlasti srednješolskemu izboru domačega in maturitetnega branja ter aktivnemu literarnemu pouku. Teksti so strokovno predstavljeni s spremnimi besedili, ki vključujejo: literarnozgodovinsko predstavitev avtorja, njegovega časa in dela, poglobljeno analizo in interpretacijo literarnih prvin zunanje in notranje zgradbe, jezika in sloga, izbor mnenj o delu, vprašanja, naloge in teme.', 'https://www.emka.si/wcsstore/MKCAS/img/catalog/9788634119060/646x1000/9788634119060.jpeg', 16, 3),
(16, 'Saloma ', 'Oscar Wilde', 'Zbirka slovenskih in svetovnih leposlovnih del je prilagojena zlasti srednješolskemu izboru domačega in maturitetnega branja ter aktivnemu literarnemu pouku. Teksti so strokovno predstavljeni s spremnimi besedili, ki vključujejo: literarnozgodovinsko predstavitev avtorja, njegovega časa in dela, poglobljeno analizo in interpretacijo literarnih prvin zunanje in notranje zgradbe, jezika in sloga, izbor mnenj o delu, vprašanja, naloge in teme.', 'Zbirka slovenskih in svetovnih leposlovnih del je prilagojena zlasti srednješolskemu izboru domačega in maturitetnega branja ter aktivnemu literarnemu pouku. Teksti so strokovno predstavljeni s spremnimi besedili, ki vključujejo: literarnozgodovinsko predstavitev avtorja, njegovega časa in dela, poglobljeno analizo in interpretacijo literarnih prvin zunanje in notranje zgradbe, jezika in sloga, izbor mnenj o delu, vprašanja, naloge in teme.', 'https://www.emka.si/wcsstore/MKCAS/img/catalog/9788634106244/646x1000/9788634106244.jpeg', 14, 3);

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `title` varchar(255) CHARACTER SET utf8 COLLATE utf8_slovenian_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

INSERT INTO `categories` (`id`, `title`) VALUES
(1, 'FANTAZIJSKE KNJIGE'),
(2, 'OTROŠKE KNJIGE'),
(3, 'DRAMA'),
(4, 'KUHINJSKE KNJIGE'),
(5, 'KOMEDIJA');

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `ime` varchar(20) CHARACTER SET utf8 COLLATE utf8_slovenian_ci NOT NULL,
  `priimek` varchar(20) CHARACTER SET utf8 COLLATE utf8_slovenian_ci NOT NULL,
  `email` varchar(255) NOT NULL,
  `starost` int(3) DEFAULT NULL,
  `password` varchar(255) CHARACTER SET utf8 COLLATE utf8_slovenian_ci NOT NULL,
  `slika` varchar(255) CHARACTER SET utf8 COLLATE utf8_slovenian_ci DEFAULT NULL,
  `role` varchar(20) CHARACTER SET utf8 COLLATE utf8_slovenian_ci NOT NULL DEFAULT 'user'
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE `books`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `books`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;

ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
